services:

  db:
    image: postgres:16-alpine
    container_name: ecommerce-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ExamDB@2026
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
    container_name: ecommerce-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 5000
      DB_URL: postgresql://ecommerce_user:ExamDB%402026@db:5432/ecommerce_db
      SESSION_SECRET: ${SESSION_SECRET}
      FRONT_DOMAIN: http://localhost:3000
      SERVER_URL: http://localhost:5000
      NODE_ENV: development
      GITHUB_CLIENT: ${GITHUB_CLIENT}
      GITHUB_SECRET: ${GITHUB_SECRET}
      STRIPE_PUBLIC: ${STRIPE_PUBLIC}
      STRIPE_SECRET: ${STRIPE_SECRET}
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
    container_name: ecommerce-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
