apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
  namespace: ecommerce

spec:
  replicas: 2

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: ecommerce-frontend

  template:
    metadata:
      labels:
        app: ecommerce-frontend

    spec:

      containers:
        - name: frontend

          image: ecommerce-frontend:v1

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          resources:

            requests:
              cpu: "100m"
              memory: "64Mi"

            limits:
              cpu: "300m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 80

            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80

            initialDelaySeconds: 20
            periodSeconds: 20
